apiVersion: 1

datasources:
  - name: Shelly InfluxDB
    uid: shelly-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: shelly
    user: ""
    secureJsonData: {}
    isDefault: true
    jsonData:
      httpMode: POST
